/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author home
 */
public class mainLogin extends javax.swing.JFrame {
    Employee user;
    EmployeeDAO ed;
    UIFaculty uiF;
    UIAdmin uiP;
    /**
     * Creates new form mainLogin
     */
    public mainLogin() {
        ed = new EmployeeDAO();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtPWord = new javax.swing.JPasswordField();
        userName = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        logIn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bLogIn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login_form = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 200, -1));

        txtPWord.setText("txtPWord");
        txtPWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPWordActionPerformed(evt);
            }
        });
        txtPWord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPWordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPWordFocusLost(evt);
            }
        });
        txtPWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPWordKeyPressed(evt);
            }
        });
        getContentPane().add(txtPWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 200, -1));

        userName.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("Username:");
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        password.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password:");
        password.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        logIn.setFont(new java.awt.Font("Prestige Elite Std", 0, 28)); // NOI18N
        logIn.setForeground(new java.awt.Color(255, 255, 255));
        logIn.setText("Log in");
        getContentPane().add(logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Prestige Elite Std", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please fill in your Basic info:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phila-logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 120, -1));

        bLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_button.png"))); // NOI18N
        bLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLogInMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bLogInMousePressed(evt);
            }
        });
        getContentPane().add(bLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Register_button.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 120, -1));

        login_form.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_form3.png"))); // NOI18N
        login_form.setText("jLabel1");
        getContentPane().add(login_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 390, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phila_bg.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
    }// </editor-fold>                        

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txtPWordActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void txtPWordFocusGained(java.awt.event.FocusEvent evt) {                                     
        String pass = String.copyValueOf(txtPWord.getPassword());

        if (pass.equals("txtPWord")) {
            txtPWord.setText("");        // TODO add your handling code here:
    }                                    
    }
    private void bLogInMousePressed(java.awt.event.MouseEvent evt) {                                    
       
    }                                   

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
        int x = JOptionPane.showConfirmDialog(null, "Will you register an account?", "Alert Message!", JOptionPane.YES_NO_OPTION);
		if (x == JOptionPane.YES_OPTION){
                    registration r = new registration();    
                    r.setVisible(true);
                    this.setVisible(false);  
                }
    }                                    

   public void LogIn()
   {user = new Employee();
            user.setUsername(txtUsername.getText().toString());
            System.out.println(txtUsername.getText().toString());
            user.setPass(String.copyValueOf(txtPWord.getPassword()));
            System.out.println(String.copyValueOf(txtPWord.getPassword()));
            user.setPosition(ed.getLoginReq(user));
            System.out.println(user.getPosition());
           if(user.getChangedPass()){
            if(user.getPosition().equals("Administrator"))
            {   
                uiP = new UIAdmin(user);
                uiP.setVisible(true);
                this.setVisible(false);
            }
            else if(user.getPosition().equals("Principal"))
                JOptionPane.showMessageDialog(null,"Principal!");
            else if(user.getPosition().equals("Coordinator"))
                JOptionPane.showMessageDialog(null,"Coordinatorl!");
            else if(user.getPosition().equals("Subject Teacher"))
            {   uiF = new UIFaculty(user);
                uiF.setVisible(true);
                this.setVisible(false);
            }
            else
                JOptionPane.showMessageDialog(null,"Invalid Username or Password!");
           }
           else
                JOptionPane.showMessageDialog(null,"Invalid Username or Password!");
   }
    private void bLogInMouseClicked(java.awt.event.MouseEvent evt) {                                    
       LogIn();
    }                                   

    private void txtPWordKeyPressed(java.awt.event.KeyEvent evt) {                                    
        
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){  
              LogIn();
        }// TODO add your handling code here:
    }                                   

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {                                        
        if(txtUsername.getText().equals("username"))
            txtUsername.setText("");
    }                                       

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {                                      
        if(txtUsername.getText().equals(""))
            txtUsername.setText("username");
    }                                     

    private void txtPWordFocusLost(java.awt.event.FocusEvent evt) {                                   
           String pass = String.copyValueOf(txtPWord.getPassword());
           if (pass.equals("")) 
            txtPWord.setText("txtPWord");    
    }                                  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel bLogIn;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logIn;
    private javax.swing.JLabel login_form;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField txtPWord;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel userName;
    // End of variables declaration                   
}
