
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author James
 */
public class UIAdmin extends javax.swing.JFrame {
    Employee user;
    Employee emp;
    Department dept;
    Course course;
    Student st;
    Section s;
    String[] sectList;
    Classroom c;
    CourseDAO coD = new CourseDAO();
    ErrorHandler eh = new ErrorHandler();
    EmployeeDAO ed = new EmployeeDAO();
    ClassroomDAO cd = new ClassroomDAO();
    StudentDAO std = new StudentDAO();
    DepartmentDAO dd = new DepartmentDAO();
    
    /**
     * Creates new form UIPrincipal
     */
      public UIAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtFPhone.setDocument(new LengthRestrictedDocument(11));
        txtFPhone.setText("Phone#");
        txtSAge.setDocument(new LengthRestrictedDocument(2));
        txtSID.setDocument(new LengthRestrictedDocument(8));
        txtSID.setText("Student#");
        txtFID.setDocument(new LengthRestrictedDocument(8));
        txtFID.setText("Faculty#");
        txtSPhone.setDocument(new LengthRestrictedDocument(11));
        txtSPhone.setText("Phone#");
    }
    public UIAdmin(Employee user) {
        this.user = user;
        initComponents();
        this.setLocationRelativeTo(null);
        txtFPhone.setDocument(new LengthRestrictedDocument(11));
        txtFPhone.setText("Phone#");
        txtSAge.setDocument(new LengthRestrictedDocument(2));
        txtSID.setDocument(new LengthRestrictedDocument(8));
        txtSID.setText("Student#");
        txtFID.setDocument(new LengthRestrictedDocument(8));
        txtFID.setText("Faculty#");
        txtSPhone.setDocument(new LengthRestrictedDocument(11));
        txtSPhone.setText("Phone#");
    }

    public void changeSection(int grade_lvl, javax.swing.JComboBox jc)
    {
        sectList  =  new String[10];
        jc.removeAllItems();
        cd.getSection(grade_lvl, sectList);
        for (String string : sectList) {
             if(string != null)
             jc.addItem(string);
        }
    }
    public void changeText(javax.swing.JTextField txtf, String from, String to)
    {
        if(txtf.getText().equals(from))
            txtf.setText(to);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lUsername = new javax.swing.JLabel();
        mainPane = new javax.swing.JTabbedPane();
        tabAccount = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        quizOption = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        reciteOption = new javax.swing.JSpinner();
        projectOption = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PTOption = new javax.swing.JSpinner();
        bUpdateGP = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        SWOption = new javax.swing.JSpinner();
        jPanel16 = new javax.swing.JPanel();
        PTOptionCQ = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        quizOptionCQ = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        ProjOptionCQ = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        bUpdateCQ = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        SWOptionCQ = new javax.swing.JSpinner();
        tabGrades = new javax.swing.JTabbedPane();
        viewFinalGradesperSection = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        gradelevel_1 = new javax.swing.JComboBox();
        section_1 = new javax.swing.JComboBox();
        bViewFGPS = new javax.swing.JButton();
        bPrintFGPS = new javax.swing.JButton();
        bSaveFGPS = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableFGPS = new javax.swing.JTable();
        viewFinalGradesperSectionperQuarter = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        gradelevel_2 = new javax.swing.JComboBox();
        section_2 = new javax.swing.JComboBox();
        bViewFGPS1 = new javax.swing.JButton();
        bPrintFGPS1 = new javax.swing.JButton();
        bSaveFGPS1 = new javax.swing.JButton();
        quarter_2 = new javax.swing.JComboBox();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableVGPSPQ = new javax.swing.JTable();
        viewIndividualGrades = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        gradelevel_3 = new javax.swing.JComboBox();
        section_3 = new javax.swing.JComboBox();
        bViewFGPS2 = new javax.swing.JButton();
        bPrintFGPS2 = new javax.swing.JButton();
        bSaveFGPS2 = new javax.swing.JButton();
        studentname_3 = new javax.swing.JComboBox();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableIndividual = new javax.swing.JTable();
        tabPerson = new javax.swing.JTabbedPane();
        tabPTeachers = new javax.swing.JTabbedPane();
        tabSAdd1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtFLastName1 = new javax.swing.JTextField();
        txtFFirstName1 = new javax.swing.JTextField();
        txtFMiddleName1 = new javax.swing.JTextField();
        txtFID = new javax.swing.JTextField();
        txtFAddress = new javax.swing.JTextField();
        txtFPhone = new javax.swing.JTextField();
        bFRegister = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        tabPSxn = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        addLevel = new javax.swing.JButton();
        addSection1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        txtSection = new javax.swing.JTextField();
        cGrade = new javax.swing.JComboBox();
        lastName1 = new javax.swing.JTextField();
        firstName1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tabAddSubjects = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        updateSubject = new javax.swing.JButton();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cGrade1 = new javax.swing.JComboBox();
        SSection1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableSubjectsTeachers = new javax.swing.JTable();
        tabPStudents = new javax.swing.JTabbedPane();
        tabSAdd = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtSLastName = new javax.swing.JTextField();
        txtSFirstName = new javax.swing.JTextField();
        txtSMiddleName = new javax.swing.JTextField();
        txtSID = new javax.swing.JTextField();
        txtSAddress = new javax.swing.JTextField();
        txtSPhone = new javax.swing.JTextField();
        bSRegister = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        SGender = new javax.swing.JComboBox();
        txtSAge = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(633, 417));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lUsername.setText("Welcome " +user.getUsername() + "!");
        getContentPane().add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 100, 20));

        mainPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        tabAccount.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Grades percentage"));
        jPanel15.setToolTipText("Grades Percentage");
        jPanel15.setName("Grades"); // NOI18N
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Quiz");
        jPanel15.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 71, -1));
        jPanel15.add(quizOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 90, -1));

        jLabel6.setText("Recitation");
        jPanel15.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 30, 71, -1));
        jPanel15.add(reciteOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 90, -1));
        jPanel15.add(projectOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 90, -1));

        jLabel7.setText("Projects");
        jPanel15.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 71, -1));

        jLabel8.setText("Periodical Test");
        jPanel15.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 61, 71, -1));
        jPanel15.add(PTOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 90, -1));

        bUpdateGP.setText("Update Settings");
        jPanel15.add(bUpdateGP, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jLabel12.setText("Seatwork");
        jPanel15.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 71, -1));
        jPanel15.add(SWOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 90, -1));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 500, 120));

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Component quantity"));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(PTOptionCQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 90, -1));

        jLabel10.setText("Projects");
        jPanel16.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 71, -1));
        jPanel16.add(quizOptionCQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, -1));

        jLabel11.setText("Periodical Test");
        jPanel16.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 71, -1));
        jPanel16.add(ProjOptionCQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 90, -1));

        jLabel9.setText("Quiz");
        jPanel16.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 71, -1));

        bUpdateCQ.setText("Update Settings");
        jPanel16.add(bUpdateCQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel13.setText("Seatwork");
        jPanel16.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 71, -1));
        jPanel16.add(SWOptionCQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 90, -1));

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 500, 110));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        tabAccount.addTab("Settings", jPanel13);

        mainPane.addTab("Account ", tabAccount);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradelevel_1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3" }));
        jPanel8.add(gradelevel_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 1, 138, -1));

        section_1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sapphire", "Emerald", "Topaz", " " }));
        jPanel8.add(section_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 1, 179, -1));

        bViewFGPS.setText("View");
        jPanel8.add(bViewFGPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 0, -1, -1));

        bPrintFGPS.setText("Print");
        jPanel8.add(bPrintFGPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 0, -1, -1));

        bSaveFGPS.setText("Save to File");
        jPanel8.add(bSaveFGPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 0, -1, -1));

        tableFGPS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Grade", "Section", "Name", "Final Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableFGPS);

        javax.swing.GroupLayout viewFinalGradesperSectionLayout = new javax.swing.GroupLayout(viewFinalGradesperSection);
        viewFinalGradesperSection.setLayout(viewFinalGradesperSectionLayout);
        viewFinalGradesperSectionLayout.setHorizontalGroup(
            viewFinalGradesperSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
            .addComponent(jScrollPane5)
        );
        viewFinalGradesperSectionLayout.setVerticalGroup(
            viewFinalGradesperSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewFinalGradesperSectionLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
        );

        tabGrades.addTab("View Final Grades per Section", viewFinalGradesperSection);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradelevel_2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3" }));
        jPanel9.add(gradelevel_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 1, 138, -1));

        section_2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sapphire", "Emerald", "Topaz", " " }));
        jPanel9.add(section_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 1, 179, -1));

        bViewFGPS1.setText("View");
        jPanel9.add(bViewFGPS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 0, -1, -1));

        bPrintFGPS1.setText("Print");
        jPanel9.add(bPrintFGPS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 0, -1, -1));

        bSaveFGPS1.setText("Save to File");
        jPanel9.add(bSaveFGPS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 0, -1, -1));

        quarter_2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1st quarter", "2nd quarter", "3rd quarter", "4th quarter", " " }));
        jPanel9.add(quarter_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 29, 179, -1));

        tableVGPSPQ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Grade Level", "Section", "Name", "Grade"
            }
        ));
        jScrollPane6.setViewportView(tableVGPSPQ);

        javax.swing.GroupLayout viewFinalGradesperSectionperQuarterLayout = new javax.swing.GroupLayout(viewFinalGradesperSectionperQuarter);
        viewFinalGradesperSectionperQuarter.setLayout(viewFinalGradesperSectionperQuarterLayout);
        viewFinalGradesperSectionperQuarterLayout.setHorizontalGroup(
            viewFinalGradesperSectionperQuarterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
            .addComponent(jScrollPane6)
        );
        viewFinalGradesperSectionperQuarterLayout.setVerticalGroup(
            viewFinalGradesperSectionperQuarterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewFinalGradesperSectionperQuarterLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
        );

        tabGrades.addTab("View FG per Section per Quarter", viewFinalGradesperSectionperQuarter);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradelevel_3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3" }));
        jPanel10.add(gradelevel_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1, 172, -1));

        section_3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sapphire", "Emerald", "Topaz", " " }));
        jPanel10.add(section_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 1, 147, -1));

        bViewFGPS2.setText("View");
        jPanel10.add(bViewFGPS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 0, -1, -1));

        bPrintFGPS2.setText("Print");
        jPanel10.add(bPrintFGPS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 0, -1, -1));

        bSaveFGPS2.setText("Save to File");
        jPanel10.add(bSaveFGPS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 0, -1, -1));

        studentname_3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Joya, Anton", "Obuchi, Kiyoshi", "Tirados, Jake", " ", " " }));
        jPanel10.add(studentname_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 325, -1));

        tableIndividual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Quiz 1", "Quiz 2", "Quiz 3", "Quiz 4", "Quiz 5", "Periodical test", "Recitation", "Attendance", "Conduct", "Project"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tableIndividual);

        javax.swing.GroupLayout viewIndividualGradesLayout = new javax.swing.GroupLayout(viewIndividualGrades);
        viewIndividualGrades.setLayout(viewIndividualGradesLayout);
        viewIndividualGradesLayout.setHorizontalGroup(
            viewIndividualGradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
            .addComponent(jScrollPane7)
        );
        viewIndividualGradesLayout.setVerticalGroup(
            viewIndividualGradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewIndividualGradesLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabGrades.addTab("View Grades per Student", viewIndividualGrades);

        mainPane.addTab("Grade Records", tabGrades);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFLastName1.setText("Last Name");
        txtFLastName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFLastName1ActionPerformed(evt);
            }
        });
        txtFLastName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFLastName1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFLastName1FocusLost(evt);
            }
        });
        jPanel4.add(txtFLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 19, 182, -1));

        txtFFirstName1.setText("First Name");
        txtFFirstName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFFirstName1ActionPerformed(evt);
            }
        });
        txtFFirstName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFFirstName1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFFirstName1FocusLost(evt);
            }
        });
        jPanel4.add(txtFFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 55, 182, -1));

        txtFMiddleName1.setText("Middle Name");
        txtFMiddleName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFMiddleName1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFMiddleName1FocusLost(evt);
            }
        });
        jPanel4.add(txtFMiddleName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 86, 182, -1));

        txtFID.setText("Faculty#");
        txtFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFIDActionPerformed(evt);
            }
        });
        txtFID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFIDFocusLost(evt);
            }
        });
        jPanel4.add(txtFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 55, 86, -1));

        txtFAddress.setText("Address");
        txtFAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAddressActionPerformed(evt);
            }
        });
        txtFAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFAddressFocusGained(evt);
            }
        });
        jPanel4.add(txtFAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 86, 249, -1));

        txtFPhone.setText("Phone#");
        txtFPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFPhoneActionPerformed(evt);
            }
        });
        txtFPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFPhoneFocusGained(evt);
            }
        });
        jPanel4.add(txtFPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 55, 153, -1));

        bFRegister.setText("Add Faculty");
        bFRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFRegisterActionPerformed(evt);
            }
        });
        jPanel4.add(bFRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 114, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Subject Teacher", "Coordinator", "Principal" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 0, 152, -1));

        jLabel18.setText("Position");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 5, -1, -1));

        jLabel19.setText("Department");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 32, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elementary", "High School", "Elementary & High School" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 30, 152, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Faculty ID", "Last Name", "First Name", "Middle Initial", "Phone Number", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabSAdd1Layout = new javax.swing.GroupLayout(tabSAdd1);
        tabSAdd1.setLayout(tabSAdd1Layout);
        tabSAdd1Layout.setHorizontalGroup(
            tabSAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabSAdd1Layout.setVerticalGroup(
            tabSAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSAdd1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPTeachers.addTab("Add", tabSAdd1);

        tabPerson.addTab("Faculty", tabPTeachers);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addLevel.setText("Add section");
        addLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLevelActionPerformed(evt);
            }
        });
        jPanel5.add(addLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 71, -1, -1));

        addSection1.setText("Update Adviser");
        addSection1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSection1ActionPerformed(evt);
            }
        });
        jPanel5.add(addSection1, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 71, 122, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Level", "Section", "Adviser"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, 638, 166));

        txtSection.setText("Section");
        txtSection.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSectionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSectionFocusLost(evt);
            }
        });
        jPanel5.add(txtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 178, -1));

        cGrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "Grade 12" }));
        jPanel5.add(cGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        lastName1.setText("Last name");
        lastName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastName1ActionPerformed(evt);
            }
        });
        lastName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastName1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastName1FocusLost(evt);
            }
        });
        jPanel5.add(lastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 120, -1));

        firstName1.setText("First name");
        firstName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName1ActionPerformed(evt);
            }
        });
        firstName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstName1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstName1FocusLost(evt);
            }
        });
        jPanel5.add(firstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 120, -1));

        jLabel3.setText("Faculty:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        tabPSxn.addTab("Add Level/Section/Adviser", jPanel5);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("Subject Name");
        jTextField1.setToolTipText("Subject Name (5 - 10 Characters)");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel7.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 12, 237, -1));

        updateSubject.setText("Add Subject");
        updateSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSubjectActionPerformed(evt);
            }
        });
        jPanel7.add(updateSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        firstName.setText("First name");
        firstName.setToolTipText("First name");
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFocusLost(evt);
            }
        });
        jPanel7.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 46, 101, -1));

        lastName.setText("Last name");
        lastName.setToolTipText("Last name");
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFocusLost(evt);
            }
        });
        jPanel7.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 46, 118, -1));

        jLabel2.setText("Faculty:");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 49, -1, -1));

        cGrade1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "Grade 12" }));
        cGrade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cGrade1ActionPerformed(evt);
            }
        });
        jPanel7.add(cGrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        SSection1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Section" }));
        changeSection(1,  SSection1);
        SSection1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSection1ActionPerformed(evt);
            }
        });
        jPanel7.add(SSection1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 150, -1));

        jButton1.setText("Add Subject Teacher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        tableSubjectsTeachers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Grade", "Section", "Subject", "Teacher"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableSubjectsTeachers);

        javax.swing.GroupLayout tabAddSubjectsLayout = new javax.swing.GroupLayout(tabAddSubjects);
        tabAddSubjects.setLayout(tabAddSubjectsLayout);
        tabAddSubjectsLayout.setHorizontalGroup(
            tabAddSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
        );
        tabAddSubjectsLayout.setVerticalGroup(
            tabAddSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAddSubjectsLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabPSxn.addTab("Add Subjects & Teachers", tabAddSubjects);

        tabPerson.addTab("Classes/Sections", tabPSxn);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSLastName.setText("Last Name");
        txtSLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLastNameActionPerformed(evt);
            }
        });
        txtSLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSLastNameFocusLost(evt);
            }
        });
        jPanel3.add(txtSLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 19, 182, -1));

        txtSFirstName.setText("First Name");
        txtSFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSFirstNameActionPerformed(evt);
            }
        });
        txtSFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSFirstNameFocusLost(evt);
            }
        });
        jPanel3.add(txtSFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 50, 182, -1));

        txtSMiddleName.setText("Middle Name");
        txtSMiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSMiddleNameActionPerformed(evt);
            }
        });
        txtSMiddleName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSMiddleNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSMiddleNameFocusLost(evt);
            }
        });
        jPanel3.add(txtSMiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 81, 182, -1));

        txtSID.setText("Student#");
        txtSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSIDActionPerformed(evt);
            }
        });
        txtSID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSIDFocusLost(evt);
            }
        });
        jPanel3.add(txtSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 50, 86, -1));

        txtSAddress.setText("Address");
        txtSAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSAddressActionPerformed(evt);
            }
        });
        txtSAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSAddressFocusGained(evt);
            }
        });
        jPanel3.add(txtSAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 81, 205, -1));

        txtSPhone.setText("Phone#");
        txtSPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSPhoneActionPerformed(evt);
            }
        });
        txtSPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSPhoneFocusLost(evt);
            }
        });
        jPanel3.add(txtSPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 50, 101, -1));

        bSRegister.setText("Add Student");
        bSRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSRegisterActionPerformed(evt);
            }
        });
        jPanel3.add(bSRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 109, -1, -1));

        jLabel22.setText("Gender");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 22, -1, -1));

        jLabel23.setText("Age");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 22, -1, -1));

        SGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        SGender.setToolTipText("");
        SGender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SGenderActionPerformed(evt);
            }
        });
        jPanel3.add(SGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 19, -1, -1));

        txtSAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSAgeActionPerformed(evt);
            }
        });
        jPanel3.add(txtSAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 19, 35, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Last Name", "First Name", "Middle Initial", "Grade Level", "Phone Number", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabSAddLayout = new javax.swing.GroupLayout(tabSAdd);
        tabSAdd.setLayout(tabSAddLayout);
        tabSAddLayout.setHorizontalGroup(
            tabSAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabSAddLayout.setVerticalGroup(
            tabSAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSAddLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPStudents.addTab("Add", tabSAdd);

        tabPerson.addTab("Students", tabPStudents);

        mainPane.addTab("Person Records", tabPerson);

        getContentPane().add(mainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 670, 430));

        bLogout.setText("Logout");
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(bLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        pack();
    }// </editor-fold>                        

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                        
         int x = JOptionPane.showConfirmDialog(null, "Will you logout?", "Alert Message!", JOptionPane.YES_NO_OPTION);
		if (x == JOptionPane.YES_OPTION){
                    this.setVisible(false);
                    mainLogin ml = new mainLogin();
                    ml.setVisible(true);
                }        // TODO add your handling code here:
    }                                       

    private void addLevelActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(eh.sCheckNames(txtSection.getText()))
        {
            s = new Section();
            s.setSectname((txtSection.getText()));
            s.setSectyear(Integer.parseInt(cGrade.getSelectedItem().toString().replace("Grade ", "")));
            System.out.println((cGrade.getSelectedItem().toString().replace("Grade ", "")));
            if(cd.addSection(s)){
            JOptionPane.showMessageDialog(rootPane, "Section has been added!");
            changeSection(Integer.parseInt(cGrade.getSelectedItem().toString().replace("Grade ", "")), SSection1);
            changeSection(Integer.parseInt(cGrade1.getSelectedItem().toString().replace("Grade ", "")), SSection1);
            }
            else
            JOptionPane.showMessageDialog(rootPane, "Section name already exists! Please choose another name.");
        }
        else
        JOptionPane.showMessageDialog(rootPane, "Invalid characters for section!");
    }                                        

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if((jComboBox1.getSelectedItem().toString().equals("Subject Teacher")))
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elementary", "High School", "Elementary & High School" }));
        else if((jComboBox1.getSelectedItem().toString().equals("Coordinator")))
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elementary", "High School" }));
        else if((jComboBox1.getSelectedItem().toString().equals("Principal")))
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "School" }));
    }                                          

    private void bFRegisterActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (eh.sCheckNames(txtFFirstName1.getText()) && eh.sCheckNames(txtFMiddleName1.getText()) && eh.sCheckNames( txtFLastName1.getText()) && (!txtFID.getText().isEmpty() && eh.sCheckCodes(txtFID.getText(), 2) && !eh.sLength(txtFID.getText(), 7,8)) && ((eh.sCheckCodes(txtFPhone.getText(), 2) && !eh.sLength(txtFPhone.getText(), 7, 11)) || txtFPhone.getText().isEmpty()))
        {
            emp = new Employee();
            emp.setLastname( txtFLastName1.getText());
            emp.setMidname(txtFMiddleName1.getText());
            emp.setFirstname(txtFFirstName1.getText());
            emp.setID(Integer.parseInt(txtFID.getText()));
            emp.setPosition(jComboBox1.getSelectedItem().toString());
            emp.setAddress(txtFAddress.getText());
            emp.setPhone((txtFPhone.getText()));
            if(txtFAddress.getText().equals("Address") || txtFAddress.getText().equals(""))
                emp.setAddress("N/A");
            if(txtFPhone.getText().equals("Phone#")|| txtFPhone.getText().equals(""))
                emp.setPhone("N/A");
            if(ed.addEmployees(emp)){
                if(jComboBox2.getSelectedItem().toString().equals("Elementary & High School") && jComboBox1.getSelectedItem().toString().equals("School Teacher")){
                    dept.setDepartmentName("Elementary");
                    dept.setEmployee(Integer.parseInt(txtFID.getText()));
                    dd.addDepartmentEmp(dept);
                    dept.setDepartmentName("High School");
                    dd.addDepartmentEmp(dept);
                }
                else
                {
                    dept = new Department();
                    dept.setDepartmentName(jComboBox2.getSelectedItem().toString());
                    dept.setEmployee(Integer.parseInt(txtFID.getText()));
                    dd.addDepartmentEmp(dept);

                }
                JOptionPane.showMessageDialog(null,"Adding successful!");
                txtFLastName1.setText("Last Name");
                txtFMiddleName1.setText("Middle Name");
                txtFFirstName1.setText("First Name");
                txtFID.setText("Faculty#");
                txtFAddress.setText("Address");
                txtFPhone.setText("Phone#");
            }
            else
            JOptionPane.showMessageDialog(null,"An error has been encountered.");
        }
        else
            JOptionPane.showMessageDialog(null, "Invalid input in one of the fields");
    }                                          

    private void txtFPhoneFocusGained(java.awt.event.FocusEvent evt) {                                      
        if((txtFPhone.getText().toString().equals("Phone#")))
        txtFPhone.setText("");             // TODO add your handling code here:
    }                                     

    private void txtFPhoneActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void txtFAddressFocusGained(java.awt.event.FocusEvent evt) {                                        
        if((txtFAddress.getText().toString().equals("Address")))
        txtFAddress.setText("");
    }                                       

    private void txtFAddressActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txtFIDFocusGained(java.awt.event.FocusEvent evt) {                                   
        if((txtFID.getText().toString().equals("Faculty#")))
        txtFID.setText("");               // TODO add your handling code here:
    }                                  

    private void txtFIDActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void txtFMiddleName1FocusGained(java.awt.event.FocusEvent evt) {                                            
        if((txtFMiddleName1.getText().toString().equals("Middle Name")))
        txtFMiddleName1.setText("");
    }                                           

    private void txtFFirstName1FocusGained(java.awt.event.FocusEvent evt) {                                           
        if((txtFFirstName1.getText().toString().equals("First Name")))
        txtFFirstName1.setText("");        // TODO add your handling code here:
    }                                          

    private void txtFFirstName1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void txtFLastName1FocusGained(java.awt.event.FocusEvent evt) {                                          
        if((txtFLastName1.getText().toString().equals("Last Name")))
        txtFLastName1.setText("");
    }                                         

    private void txtFLastName1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void txtSLastNameActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void txtSFirstNameActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void txtSMiddleNameActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void txtSIDActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void txtSAddressActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txtSPhoneActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void bSRegisterActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (eh.sCheckNames(txtSFirstName.getText()) && eh.sCheckNames(txtSLastName.getText()) && eh.sCheckNames( txtSMiddleName.getText()) && (eh.sCheckCodes(txtSID.getText(), 2) && !eh.sLength(txtSID.getText(), 6, 8))  && eh.sCheckCodes(txtSPhone.getText(), 2) && Integer.parseInt(txtSAge.getText()) > 0 && eh.sCheckCodes(txtSAge.getText(), 2))
        {
            st = new Student();
            st.setID(Integer.parseInt(txtSID.getText()));
            st.setFirstname(txtSFirstName.getText());
            st.setMidname(txtSMiddleName.getText());
            st.setLastname(txtSLastName.getText());
            st.setGender((SGender.getSelectedItem().toString()));
            st.setAge(Integer.parseInt((txtSAge.getText())));
            st.setPhone((txtSPhone.getText()));
            st.setAddress(txtSAddress.getText());
            st.setEnrolled(true);
            if(std.addStudent(st))
            {
                JOptionPane.showMessageDialog(rootPane, "Student has been added!");
                 txtSID.setText("Student#");
                 txtSFirstName.setText("First Name");
                 txtSMiddleName.setText("Middle Name");
                 txtSLastName.setText("Last Name");
                 txtSPhone.setText("Phone#");
                 txtSAddress.setText("Address");
                 txtSAge.setText("");
            }
        }
        else
        JOptionPane.showMessageDialog(rootPane, "One of the fields is invalid!" );
    }                                          

    private void SGenderActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtSAgeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void addSection1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        if(eh.sCheckNames(txtSection.getText()))
        {
            s = new Section();
            emp = new Employee();
            s.setSectname((txtSection.getText()));
            s.setSectyear(Integer.parseInt(cGrade.getSelectedItem().toString().replace("Grade ", "")));
            emp.setFirstname(firstName1.getText());
            emp.setLastname(lastName1.getText());
            ed.getEmpInfo(emp);
            c = new Classroom(s, emp);
            if(cd.addAdviser(c)){
                JOptionPane.showMessageDialog(rootPane, "Adviser has been added!");
                firstName1.setText("First name");
                lastName1.setText("Last name");
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Section may have an adviser already or faculty is invalid!");
        }
        else
        JOptionPane.showMessageDialog(rootPane, "Invalid section!");
    }                                           

    private void cGrade1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        changeSection(Integer.parseInt(cGrade1.getSelectedItem().toString().replace("Grade ", "")), SSection1);
    }                                       

    private void SSection1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void updateSubjectActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if(eh.sCheckCodes(jTextField1.getText(),1) && !eh.sLength(jTextField1.getText(), 4,15))
        {
            course = new Course();
            course.setCoursename(jTextField1.getText());
            if(coD.addCourse(course))
                JOptionPane.showMessageDialog(rootPane, "Course has been added.");
            else
                JOptionPane.showMessageDialog(rootPane, "Course already exists.");
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Invalid input for course.");
    }                                             

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        emp = new Employee();
        s = new Section();
        course = new Course();
        s.setSectyear(Integer.parseInt(cGrade1.getSelectedItem().toString().replace("Grade ", "")));
        s.setSectname(SSection1.getSelectedItem().toString());
        emp.setLastname(lastName.getText());
        emp.setFirstname(firstName.getText());
        if(ed.getEmpInfo(emp)){
        course.setCoursename(jTextField1.getText());
        c = new Classroom(s,emp,course);
        if(cd.addSubjTeach(c))
            JOptionPane.showMessageDialog(rootPane, "Subject teacher has been added!");
        else
            JOptionPane.showMessageDialog(rootPane, "Subject may not exist or there's a duplicate.");
        }
        else 
            JOptionPane.showMessageDialog(rootPane, "No such faculty name exists!");
    }                                        

    private void txtSectionFocusGained(java.awt.event.FocusEvent evt) {                                       
         changeText(txtSection, "Section", "");
    }                                      

    private void txtSectionFocusLost(java.awt.event.FocusEvent evt) {                                     
        changeText(txtSection, "", "Section");
    }                                    

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {                                        
       changeText(jTextField1, "Subject Name", "");
    }                                       

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {                                      
        changeText(jTextField1, "", "Subject Name");
    }                                     

    private void txtSIDFocusGained(java.awt.event.FocusEvent evt) {                                   
       changeText(txtSID,"Student#", "");
    }                                  

    private void txtSIDFocusLost(java.awt.event.FocusEvent evt) {                                 
        changeText(txtSID,"","Student#");
    }                                

    private void txtSPhoneFocusGained(java.awt.event.FocusEvent evt) {                                      
       changeText(txtSPhone,"Phone#","");
    }                                     

    private void txtSPhoneFocusLost(java.awt.event.FocusEvent evt) {                                    
 
    }                                   

    private void txtSLastNameFocusGained(java.awt.event.FocusEvent evt) {                                         
       changeText(txtSLastName,"Last Name","");
    }                                        

    private void txtSLastNameFocusLost(java.awt.event.FocusEvent evt) {                                       
        changeText(txtSLastName,"","Last Name");
    }                                      

    private void txtSFirstNameFocusGained(java.awt.event.FocusEvent evt) {                                          
       changeText(txtSFirstName,"First Name","");
    }                                         

    private void txtSFirstNameFocusLost(java.awt.event.FocusEvent evt) {                                        
        changeText(txtSFirstName,"","First Name");
    }                                       

    private void txtSMiddleNameFocusGained(java.awt.event.FocusEvent evt) {                                           
      changeText(txtSMiddleName,"Middle Name","");
    }                                          

    private void txtSMiddleNameFocusLost(java.awt.event.FocusEvent evt) {                                         
        changeText(txtSMiddleName,"","Middle Name");
    }                                        

    private void txtSAddressFocusGained(java.awt.event.FocusEvent evt) {                                        
        changeText(txtSAddress, "Address", ""); 
    }                                       

    private void txtFLastName1FocusLost(java.awt.event.FocusEvent evt) {                                        
        changeText(txtFLastName1,"","Last Name");        // TODO add your handling code here:
    }                                       

    private void txtFFirstName1FocusLost(java.awt.event.FocusEvent evt) {                                         
        changeText(txtFFirstName1,"","First Name");
    }                                        

    private void txtFMiddleName1FocusLost(java.awt.event.FocusEvent evt) {                                          
        changeText(txtFMiddleName1,"","Middle Name");
    }                                         

    private void txtFIDFocusLost(java.awt.event.FocusEvent evt) {                                 
        changeText(txtFID,"","Faculty#");        // TODO add your handling code here:
    }                                

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void lastNameFocusLost(java.awt.event.FocusEvent evt) {                                   
        changeText(lastName, "Last name", "");
    }                                  

    private void lastNameFocusGained(java.awt.event.FocusEvent evt) {                                     
        changeText(lastName, "Last name", "");
    }                                    

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void firstNameFocusLost(java.awt.event.FocusEvent evt) {                                    
        changeText(firstName, "", "First name");
    }                                   

    private void firstNameFocusGained(java.awt.event.FocusEvent evt) {                                      
        if (firstName.getText().equals("First name")) {
            firstName.setText("");
        }// TODO add your handling code here:
    }                                     

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void lastName1FocusLost(java.awt.event.FocusEvent evt) {                                    
        changeText(lastName1, "", "Last name");        // TODO add your handling code here:
    }                                   

    private void lastName1FocusGained(java.awt.event.FocusEvent evt) {                                      
        changeText(lastName1, "Last name", "");
    }                                     

    private void lastName1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void firstName1FocusLost(java.awt.event.FocusEvent evt) {                                     
        changeText(firstName1, "", "First name");
    }                                    

    private void firstName1FocusGained(java.awt.event.FocusEvent evt) {                                       
        changeText(firstName1, "First name", "");
    }                                      

    private void firstName1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JSpinner PTOption;
    private javax.swing.JSpinner PTOptionCQ;
    private javax.swing.JSpinner ProjOptionCQ;
    private javax.swing.JComboBox SGender;
    private javax.swing.JComboBox SSection1;
    private javax.swing.JSpinner SWOption;
    private javax.swing.JSpinner SWOptionCQ;
    private javax.swing.JButton addLevel;
    private javax.swing.JButton addSection1;
    private javax.swing.JButton bFRegister;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bPrintFGPS;
    private javax.swing.JButton bPrintFGPS1;
    private javax.swing.JButton bPrintFGPS2;
    private javax.swing.JButton bSRegister;
    private javax.swing.JButton bSaveFGPS;
    private javax.swing.JButton bSaveFGPS1;
    private javax.swing.JButton bSaveFGPS2;
    private javax.swing.JButton bUpdateCQ;
    private javax.swing.JButton bUpdateGP;
    private javax.swing.JButton bViewFGPS;
    private javax.swing.JButton bViewFGPS1;
    private javax.swing.JButton bViewFGPS2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cGrade;
    private javax.swing.JComboBox cGrade1;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField firstName1;
    private javax.swing.JComboBox gradelevel_1;
    private javax.swing.JComboBox gradelevel_2;
    private javax.swing.JComboBox gradelevel_3;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lUsername;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField lastName1;
    private javax.swing.JTabbedPane mainPane;
    private javax.swing.JSpinner projectOption;
    private javax.swing.JComboBox quarter_2;
    private javax.swing.JSpinner quizOption;
    private javax.swing.JSpinner quizOptionCQ;
    private javax.swing.JSpinner reciteOption;
    private javax.swing.JComboBox section_1;
    private javax.swing.JComboBox section_2;
    private javax.swing.JComboBox section_3;
    private javax.swing.JComboBox studentname_3;
    private javax.swing.JTabbedPane tabAccount;
    private javax.swing.JPanel tabAddSubjects;
    private javax.swing.JTabbedPane tabGrades;
    private javax.swing.JTabbedPane tabPStudents;
    private javax.swing.JTabbedPane tabPSxn;
    private javax.swing.JTabbedPane tabPTeachers;
    private javax.swing.JTabbedPane tabPerson;
    private javax.swing.JPanel tabSAdd;
    private javax.swing.JPanel tabSAdd1;
    private javax.swing.JTable tableFGPS;
    private javax.swing.JTable tableIndividual;
    private javax.swing.JTable tableSubjectsTeachers;
    private javax.swing.JTable tableVGPSPQ;
    private javax.swing.JTextField txtFAddress;
    private javax.swing.JTextField txtFFirstName1;
    private javax.swing.JTextField txtFID;
    private javax.swing.JTextField txtFLastName1;
    private javax.swing.JTextField txtFMiddleName1;
    private javax.swing.JTextField txtFPhone;
    private javax.swing.JTextField txtSAddress;
    private javax.swing.JTextField txtSAge;
    private javax.swing.JTextField txtSFirstName;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtSLastName;
    private javax.swing.JTextField txtSMiddleName;
    private javax.swing.JTextField txtSPhone;
    private javax.swing.JTextField txtSection;
    private javax.swing.JButton updateSubject;
    private javax.swing.JPanel viewFinalGradesperSection;
    private javax.swing.JPanel viewFinalGradesperSectionperQuarter;
    private javax.swing.JPanel viewIndividualGrades;
    // End of variables declaration                   
}
