
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author James
 */
public class UIFaculty extends javax.swing.JFrame {

    /**
     * Creates new form UIAdmin
     */
    Employee user;
    ErrorHandler eh = new ErrorHandler();
    Student st;
    Section s;
    String[] sectList;
    String[] subjList;
    Classroom c;
    Grade g;
    Course course;
    ClassroomDAO cd = new ClassroomDAO();
    StudentDAO std = new StudentDAO();
    GradeDAO gd = new GradeDAO();
     DefaultTableModel tab = new DefaultTableModel(){
           @Override
        public boolean isCellEditable(int row, int column) {
               return column == 2;
         }
     };
     public UIFaculty() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextField1.setDocument(new LengthRestrictedDocument(2));
        jTextField1.setText("Q#");
        txtSID.setDocument(new LengthRestrictedDocument(8));
        txtSID.setText("Student#");
        txtSPhone.setDocument(new LengthRestrictedDocument(11));
        txtSPhone.setText("Phone#");
        txtSAge.setDocument(new LengthRestrictedDocument(2));
    }
    public UIFaculty(Employee user) {
        this.user = user;
        initComponents();
        this.setLocationRelativeTo(null);
        jTextField1.setDocument(new LengthRestrictedDocument(2));
        jTextField1.setText("Q#");
        txtSID.setDocument(new LengthRestrictedDocument(8));
        txtSID.setText("Student#");
        txtSPhone.setDocument(new LengthRestrictedDocument(11));
        txtSPhone.setText("Phone#");
        txtSAge.setDocument(new LengthRestrictedDocument(2));
    }
    
     public void changeSection(int grade_lvl, javax.swing.JComboBox jc)
    {
        sectList  =  new String[10];
        jc.removeAllItems();
        cd.getSection(grade_lvl, sectList);
        for (String string : sectList) {
             if(string != null)
             jc.addItem(string);
        }
    }
     public void changeSubj()
     {
        subjList = new String[20];
        GSSubj.removeAllItems();
        cd.getSubjectInfo(user, subjList);
         for (String string : subjList) {
             if(string != null)
             GSSubj.addItem(string);
        }
     }
     public ArrayList<Student> getStudent()
     {
         s = new Section();
         ArrayList<Student> studentList;
         studentList = new ArrayList<Student>();
         String[] x;
         x = getSSect();
         s.setSectname(x[1]);
         c = new Classroom(s, user);
         studentList = cd.getStudent(c);
         return studentList;
     }
     public void changeTable()
     {
          ArrayList<Student> studentList;
         studentList = new ArrayList<Student>();
         studentList = getStudent();


       
         
        Object[] tableColumnNames = new Object[3];
        tableColumnNames[0] = "Student ID";
        tableColumnNames[1] = "Student Name";
        tableColumnNames[2] = "Grade";
        tab.setColumnIdentifiers(tableColumnNames);
        Object[] objects = new Object[3];
        if (studentList.size() > 0) {
            for (int i = 0; i < studentList.size(); i++) {
                objects[0] = studentList.get(i).getId();
                objects[1] = (studentList.get(i).getFirstname() + " "+ studentList.get(i).getLastname());
                objects[2] = "";
                tab.isCellEditable(i, 3);
                tab.addRow(objects);
            }
            this.sNameGrade.setModel(tab);
        }
         
        }


     public String[] getSSect()
     {
            return GSSubj.getSelectedItem().toString().split("/");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        mainPane = new javax.swing.JTabbedPane();
        tabAccount = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jPanel20 = new javax.swing.JPanel();
        accountName = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tabGrades = new javax.swing.JTabbedPane();
        inputGrades = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        GSSubj = new javax.swing.JComboBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        sNameGrade = new javax.swing.JTable();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        bViewFGPS3 = new javax.swing.JButton();
        viewIndividualGrades = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        gradelevel_3 = new javax.swing.JComboBox();
        section_3 = new javax.swing.JComboBox();
        bViewFGPS2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableIndividual = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        viewFinalGradesperSection = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        gradelevel_1 = new javax.swing.JComboBox();
        section_1 = new javax.swing.JComboBox();
        bViewFGPS = new javax.swing.JButton();
        bPrintFGPS = new javax.swing.JButton();
        bSaveFGPS = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableFGPS = new javax.swing.JTable();
        viewFinalGradesperSectionperQuarter = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        gradelevel_2 = new javax.swing.JComboBox();
        section_2 = new javax.swing.JComboBox();
        bViewFGPS1 = new javax.swing.JButton();
        bPrintFGPS1 = new javax.swing.JButton();
        bSaveFGPS1 = new javax.swing.JButton();
        quarter_2 = new javax.swing.JComboBox();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableVGPSPQ = new javax.swing.JTable();
        tabPerson = new javax.swing.JTabbedPane();
        tabPStudents = new javax.swing.JTabbedPane();
        tabSAdd = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtSLastName = new javax.swing.JTextField();
        txtSFirstName = new javax.swing.JTextField();
        txtSMiddleName = new javax.swing.JTextField();
        SGrade = new javax.swing.JComboBox();
        txtSID = new javax.swing.JTextField();
        txtSAddress = new javax.swing.JTextField();
        txtSPhone = new javax.swing.JTextField();
        bSRegister = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        SGender = new javax.swing.JComboBox();
        txtSAge = new javax.swing.JTextField();
        SSection = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bLogout = new javax.swing.JButton();
        lUsername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jason Cruz");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 20, -1, -1));

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Notifications"));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));

        accountName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        accountName.setText((user.getFirstname() +" " + (user.getMidname()) + " " + (user.getLastname())));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountName)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountName, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel6.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));

        jLabel14.setText("Faculty ID: " + user.getID());

        jLabel15.setText("Position: " + user.getPosition());

        jLabel16.setText("Contact number: " + user.getPhone());

        jLabel17.setText("Address :" + user.getAddress() );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, 290, 200));

        tabAccount.addTab("Information", jPanel6);

        mainPane.addTab("Account ", tabAccount);

        inputGrades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GSSubj.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade/Section/Subject" }));
        GSSubj.setToolTipText("format is Grade/Section/Subject");
        changeSubj();
        GSSubj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GSSubjActionPerformed(evt);
            }
        });
        jPanel14.add(GSSubj, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 170, -1));

        inputGrades.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 30));

        sNameGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sNameGrade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sNameGradeFocusGained(evt);
            }
        });
        jScrollPane8.setViewportView(sNameGrade);
        if (sNameGrade.getColumnModel().getColumnCount() > 0) {
            sNameGrade.getColumnModel().getColumn(0).setResizable(false);
            sNameGrade.getColumnModel().getColumn(1).setResizable(false);
        }

        inputGrades.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 690, 140));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Quiz", "Homeworks", "Seatworks", "Class Participation", "Periodic Test" }));
        jComboBox3.setToolTipText("Component Type");
        inputGrades.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 170, -1));

        jTextField1.setText("Q#");
        jTextField1.setToolTipText("Component #");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        inputGrades.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 140, -1));

        bViewFGPS3.setText("Add");
        bViewFGPS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bViewFGPS3ActionPerformed(evt);
            }
        });
        inputGrades.add(bViewFGPS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 80, 30));

        tabGrades.addTab("Input Grades", inputGrades);

        viewIndividualGrades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradelevel_3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3" }));
        jPanel10.add(gradelevel_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 172, -1));

        section_3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sapphire", "Emerald", "Topaz", " " }));
        jPanel10.add(section_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 1, 147, -1));

        bViewFGPS2.setText("View");
        jPanel10.add(bViewFGPS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 0, -1, -1));

        viewIndividualGrades.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 725, -1));

        tableIndividual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Q1", "Q2", "Q3", "Q4", "Q5", "SW1", "SW2", "SW3", "SW4", "SW5", "HW1", "HW2", "HW3", "HW4", "HW5", "Periodic Grade", "Class Pariticpation", "Conduct Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tableIndividual);
        if (tableIndividual.getColumnModel().getColumnCount() > 0) {
            tableIndividual.getColumnModel().getColumn(18).setResizable(false);
        }

        viewIndividualGrades.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 740, 120));

        jLabel3.setText("Student Information:");
        viewIndividualGrades.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 30));

        jLabel4.setText("Name:");
        viewIndividualGrades.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Grades:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 20));

        jLabel6.setText("Average Grade on Quizzes:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel8.setText("Average Grade on Seatworks:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jLabel9.setText("Average Grade on Homeworks:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel10.setText("Periodical Test:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jLabel11.setText("89");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 50, -1));

        jLabel12.setText("95");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 40, -1));

        jLabel13.setText("86");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 40, -1));

        jLabel18.setText("95");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 40, -1));

        viewIndividualGrades.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 410, 120));

        jLabel19.setText("Jason Cruz");
        viewIndividualGrades.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel20.setText("Gender:");
        viewIndividualGrades.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel21.setText("Male");
        viewIndividualGrades.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 60, -1));

        tabGrades.addTab("View Grades per Class", viewIndividualGrades);

        viewFinalGradesperSection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradelevel_1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3" }));
        jPanel8.add(gradelevel_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 1, 138, -1));

        section_1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sapphire", "Emerald", "Topaz", " " }));
        jPanel8.add(section_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 1, 179, -1));

        bViewFGPS.setText("View");
        jPanel8.add(bViewFGPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 0, -1, -1));

        bPrintFGPS.setText("Print");
        jPanel8.add(bPrintFGPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 0, -1, -1));

        bSaveFGPS.setText("Save to File");
        jPanel8.add(bSaveFGPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 0, -1, -1));

        viewFinalGradesperSection.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 725, -1));

        tableFGPS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Grade", "Section", "Name", "Final Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableFGPS);

        viewFinalGradesperSection.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 725, 270));

        tabGrades.addTab("View Final Grades per Section", viewFinalGradesperSection);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradelevel_2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3" }));
        jPanel9.add(gradelevel_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 1, 138, -1));

        section_2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sapphire", "Emerald", "Topaz", " " }));
        jPanel9.add(section_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 1, 179, -1));

        bViewFGPS1.setText("View");
        jPanel9.add(bViewFGPS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 0, -1, -1));

        bPrintFGPS1.setText("Print");
        jPanel9.add(bPrintFGPS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 0, -1, -1));

        bSaveFGPS1.setText("Save to File");
        jPanel9.add(bSaveFGPS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 0, -1, -1));

        quarter_2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1st quarter", "2nd quarter", "3rd quarter", "4th quarter", " " }));
        jPanel9.add(quarter_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 29, 179, -1));

        tableVGPSPQ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Grade Level", "Section", "Name", "Grade"
            }
        ));
        jScrollPane6.setViewportView(tableVGPSPQ);

        javax.swing.GroupLayout viewFinalGradesperSectionperQuarterLayout = new javax.swing.GroupLayout(viewFinalGradesperSectionperQuarter);
        viewFinalGradesperSectionperQuarter.setLayout(viewFinalGradesperSectionperQuarterLayout);
        viewFinalGradesperSectionperQuarterLayout.setHorizontalGroup(
            viewFinalGradesperSectionperQuarterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addComponent(jScrollPane6)
        );
        viewFinalGradesperSectionperQuarterLayout.setVerticalGroup(
            viewFinalGradesperSectionperQuarterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewFinalGradesperSectionperQuarterLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
        );

        tabGrades.addTab("View FG per Section per Quarter", viewFinalGradesperSectionperQuarter);

        mainPane.addTab("Grade Records", tabGrades);

        txtSLastName.setText("Last Name");
        txtSLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLastNameActionPerformed(evt);
            }
        });
        txtSLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSLastNameFocusLost(evt);
            }
        });

        txtSFirstName.setText("First Name");
        txtSFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSFirstNameActionPerformed(evt);
            }
        });
        txtSFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSFirstNameFocusLost(evt);
            }
        });

        txtSMiddleName.setText("Middle Name");
        txtSMiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSMiddleNameActionPerformed(evt);
            }
        });
        txtSMiddleName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSMiddleNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSMiddleNameFocusLost(evt);
            }
        });

        SGrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "Grade 12", " " }));
        SGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SGradeActionPerformed(evt);
            }
        });

        txtSID.setText("Student#");
        txtSID.setToolTipText("Student ID Number(7 - 8 numbers)");
        txtSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSIDActionPerformed(evt);
            }
        });
        txtSID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSIDFocusLost(evt);
            }
        });

        txtSAddress.setText("Address");
        txtSAddress.setToolTipText("Address");
        txtSAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSAddressActionPerformed(evt);
            }
        });
        txtSAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSAddressFocusGained(evt);
            }
        });

        txtSPhone.setText("Phone#");
        txtSPhone.setToolTipText("Contact Number");
        txtSPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSPhoneActionPerformed(evt);
            }
        });
        txtSPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSPhoneFocusGained(evt);
            }
        });

        bSRegister.setText("Add Student");
        bSRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSRegisterActionPerformed(evt);
            }
        });

        jLabel22.setText("Gender");

        jLabel23.setText("Age");

        SGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        SGender.setToolTipText("");
        SGender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SGenderActionPerformed(evt);
            }
        });

        txtSAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSAgeActionPerformed(evt);
            }
        });

        SSection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Section" }));
        changeSection(1, SSection);
        SSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSectionActionPerformed(evt);
            }
        });

        jButton1.setText("Add to Class");
        jButton1.setToolTipText("Will only work if an adviser exist for that class");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bSRegister)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSAddress)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(SGrade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(SSection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(txtSAge)))
                        .addContainerGap(91, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(SGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtSAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSRegister)
                    .addComponent(jButton1)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Last Name", "First Name", "Middle Initial", "Grade Level", "Phone Number", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabSAddLayout = new javax.swing.GroupLayout(tabSAdd);
        tabSAdd.setLayout(tabSAddLayout);
        tabSAddLayout.setHorizontalGroup(
            tabSAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabSAddLayout.setVerticalGroup(
            tabSAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSAddLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPStudents.addTab("Add", tabSAdd);

        tabPerson.addTab("Students", tabPStudents);

        mainPane.addTab("Person Records", tabPerson);

        getContentPane().add(mainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 700, 390));

        bLogout.setText("Logout");
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(bLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        lUsername.setText("Welcome " +user.getUsername() + "!");
        getContentPane().add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>                        

    private void txtSLastNameActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void txtSFirstNameActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void txtSMiddleNameActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void txtSIDActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void txtSAddressActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txtSPhoneActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void SGenderActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtSAgeActionPerformed(java.awt.event.ActionEvent evt) {                                        
            // TODO add your handling code here:
    }                                       

    private void bSRegisterActionPerformed(java.awt.event.ActionEvent evt) {                                           
         if (eh.sCheckNames(txtSFirstName.getText()) && eh.sCheckNames(txtSLastName.getText()) && eh.sCheckNames( txtSMiddleName.getText()) && (eh.sCheckCodes(txtSID.getText(), 2) && !eh.sLength(txtSID.getText(), 6, 8)) && eh.sCheckCodes(txtSPhone.getText(), 2) &&  eh.sCheckCodes(txtSAge.getText(), 2) && Integer.parseInt(txtSAge.getText()) > 0 )
        {
            st = new Student();
            s = new Section();
            st.setID(Integer.parseInt(txtSID.getText()));
            st.setFirstname(txtSFirstName.getText());
            st.setMidname(txtSMiddleName.getText());
            st.setLastname(txtSLastName.getText());
            st.setGender((SGender.getSelectedItem().toString()));
            st.setAge(Integer.parseInt((txtSAge.getText())));
            st.setGradelevel(Integer.parseInt(SGrade.getSelectedItem().toString().replace("Grade ", "")));
            if(!txtSPhone.getText().isEmpty())
                st.setPhone((txtSPhone.getText()));
            else
                st.setPhone("N/A");
            if(!txtSAddress.getText().isEmpty())
                st.setAddress(txtSAddress.getText());
            else
                st.setAddress("N/A");
            if(std.addStudent(st))
            {
                JOptionPane.showMessageDialog(rootPane, "Student has been added!");
                
                 txtSID.setText("Student#");
                 txtSFirstName.setText("First Name");
                 txtSMiddleName.setText("Middle Name");
                 txtSLastName.setText("Last Name");
                 txtSPhone.setText("Phone#");
                 txtSAddress.setText("Address");
                 txtSAge.setText("");
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Student already exists.");
        }
         else
               JOptionPane.showMessageDialog(rootPane, "One/Some of the fields is/are invalid!" );
    }                                          

    private void SSectionActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void SGradeActionPerformed(java.awt.event.ActionEvent evt) {                                       
            changeSection(Integer.parseInt(SGrade.getSelectedItem().toString().replace("Grade ", "")), SSection);
    }                                      

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (eh.sCheckNames(txtSFirstName.getText()) && eh.sCheckNames(txtSLastName.getText()) && eh.sCheckNames( txtSMiddleName.getText()) &&( eh.sCheckCodes(txtSID.getText(), 2) && !eh.sLength(txtSID.getText(), 6, 8)))
        {
            st = new Student();
            s = new Section();
            st.setID(Integer.parseInt(txtSID.getText()));
            st.setFirstname(txtSFirstName.getText());
            st.setMidname(txtSMiddleName.getText());
            st.setLastname(txtSLastName.getText());
            st.setGradelevel(Integer.parseInt(SGrade.getSelectedItem().toString().replace("Grade ", "")));
            s.setSectyear(Integer.parseInt(SGrade.getSelectedItem().toString().replace("Grade ", "")));
            s.setSectname((SSection.getSelectedItem().toString()));
            c = new Classroom(s,st);
            if(cd.addtoClass(c))
            {  
                std.addStudent(st);
                JOptionPane.showMessageDialog(rootPane, "Student has been added to your class!");
                 txtSID.setText("Student#");
                 txtSFirstName.setText("First Name");
                 txtSMiddleName.setText("Middle Name");
                 txtSLastName.setText("Last Name");
                 txtSPhone.setText("Phone#");
                 txtSAddress.setText("Address");
                 txtSAge.setText("");
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Student may already be in a class or student does not exist.");
        }
         else
               JOptionPane.showMessageDialog(rootPane, "One/Some of the fields is/are invalid!" );
    }                                        

    public void changeText(javax.swing.JTextField txtf, String from, String to)
    {
        if(txtf.getText().equals(from))
            txtf.setText(to);
        
    }
    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {                                        
        changeText(jTextField1, "Q#", "");
    }                                       

    private void txtSLastNameFocusGained(java.awt.event.FocusEvent evt) {                                         
        changeText(txtSLastName, "Last Name", "");
    }                                        

    private void txtSLastNameFocusLost(java.awt.event.FocusEvent evt) {                                       
       changeText(txtSLastName,  "", "Last Name"); 
    }                                      

    private void txtSFirstNameFocusGained(java.awt.event.FocusEvent evt) {                                          
       changeText(txtSFirstName,  "First Name",""); 
    }                                         

    private void txtSFirstNameFocusLost(java.awt.event.FocusEvent evt) {                                        
        changeText(txtSFirstName, "", "First Name");
    }                                       

    private void txtSMiddleNameFocusGained(java.awt.event.FocusEvent evt) {                                           
        changeText(txtSMiddleName, "Middle Name", ""); 
    }                                          

    private void txtSMiddleNameFocusLost(java.awt.event.FocusEvent evt) {                                         
        changeText(txtSMiddleName, "", "Middle Name"); 
    }                                        

    private void txtSIDFocusGained(java.awt.event.FocusEvent evt) {                                   
       changeText(txtSID, "Student#", ""); 
    }                                  

    private void txtSIDFocusLost(java.awt.event.FocusEvent evt) {                                 
        changeText(txtSID, "", "Student#"); 
    }                                

    private void txtSAddressFocusGained(java.awt.event.FocusEvent evt) {                                        
      changeText(txtSAddress, "Address", ""); 
    }                                       

    private void txtSPhoneFocusGained(java.awt.event.FocusEvent evt) {                                      
        changeText(txtSPhone, "Phone#", ""); 
    }                                     

    private void bViewFGPS3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (sNameGrade.isEditing())
              sNameGrade.getCellEditor().stopCellEditing();
        if(eh.sCheckCodes(jTextField1.getText(), 2) && !jTextField1.getText().isEmpty() && !eh.sLength(jTextField1.getText(), 1, 10))
                {
                    if((Integer.parseInt(sNameGrade.getValueAt(sNameGrade.getSelectedRow(), 2).toString())) < 101 &&(Integer.parseInt(sNameGrade.getValueAt(sNameGrade.getSelectedRow(), 2).toString())) > -1)
                    {
                    String[] gradeSSubj;
                    g = new Grade();
                    course = new Course();
                    s = new Section();
                    st = new Student();
                    gradeSSubj = getSSect();
                    s.setSectyear(Integer.parseInt(gradeSSubj[0]));
                    s.setSectname(gradeSSubj[1]);
                    course.setCoursename(gradeSSubj[2]);
                    st.setID((Integer.parseInt(sNameGrade.getValueAt(sNameGrade.getSelectedRow(), 0).toString())));
                    g.setSt_grade((Integer.parseInt(sNameGrade.getValueAt(sNameGrade.getSelectedRow(), 2).toString())));
                    g.setGrade_type(jComboBox3.getSelectedItem().toString());
                    g.setGrade_number(Integer.parseInt(jTextField1.getText()));
                    c = new Classroom(s,  st, user, course);
                    g.setRoom(c);
                   if(gd.addGradeComp(g))
                    JOptionPane.showMessageDialog(rootPane, "Grade has been added!");
                   else
                       JOptionPane.showMessageDialog(rootPane, "Grade already exist for that student");
                    }
                    else
                        JOptionPane.showMessageDialog(rootPane, "Invalid grade value.");
                }
      else
            JOptionPane.showMessageDialog(rootPane, "Invalid component number.");
    }                                          

    private void GSSubjActionPerformed(java.awt.event.ActionEvent evt) {                                       
            changeTable();
    }                                      

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                        
                    int x = JOptionPane.showConfirmDialog(null, "Will you logout?", "Alert Message!", JOptionPane.YES_NO_OPTION);
		if (x == JOptionPane.YES_OPTION){
                    this.setVisible(false);
                    mainLogin ml = new mainLogin();
                    ml.setVisible(true);
                }             // TODO add your handling code here:
    }                                       

    private void sNameGradeFocusGained(java.awt.event.FocusEvent evt) {                                       
          sNameGrade.setValueAt("", sNameGrade.getSelectedRow(), 2);
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox GSSubj;
    private javax.swing.JComboBox SGender;
    private javax.swing.JComboBox SGrade;
    private javax.swing.JComboBox SSection;
    private javax.swing.JLabel accountName;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bPrintFGPS;
    private javax.swing.JButton bPrintFGPS1;
    private javax.swing.JButton bSRegister;
    private javax.swing.JButton bSaveFGPS;
    private javax.swing.JButton bSaveFGPS1;
    private javax.swing.JButton bViewFGPS;
    private javax.swing.JButton bViewFGPS1;
    private javax.swing.JButton bViewFGPS2;
    private javax.swing.JButton bViewFGPS3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox gradelevel_1;
    private javax.swing.JComboBox gradelevel_2;
    private javax.swing.JComboBox gradelevel_3;
    private javax.swing.JPanel inputGrades;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lUsername;
    private javax.swing.JTabbedPane mainPane;
    private javax.swing.JComboBox quarter_2;
    private javax.swing.JTable sNameGrade;
    private javax.swing.JComboBox section_1;
    private javax.swing.JComboBox section_2;
    private javax.swing.JComboBox section_3;
    private javax.swing.JTabbedPane tabAccount;
    private javax.swing.JTabbedPane tabGrades;
    private javax.swing.JTabbedPane tabPStudents;
    private javax.swing.JTabbedPane tabPerson;
    private javax.swing.JPanel tabSAdd;
    private javax.swing.JTable tableFGPS;
    private javax.swing.JTable tableIndividual;
    private javax.swing.JTable tableVGPSPQ;
    private javax.swing.JTextField txtSAddress;
    private javax.swing.JTextField txtSAge;
    private javax.swing.JTextField txtSFirstName;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtSLastName;
    private javax.swing.JTextField txtSMiddleName;
    private javax.swing.JTextField txtSPhone;
    private javax.swing.JPanel viewFinalGradesperSection;
    private javax.swing.JPanel viewFinalGradesperSectionperQuarter;
    private javax.swing.JPanel viewIndividualGrades;
    // End of variables declaration                   
}
